package org.aktin.broker.query.aggregate.rscript;

import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement(name=RSource.XML_ELEMENT)
public class RSource {
	public static final String XML_ELEMENT = "r-script";
	public static final String XML_NAMESPACE = "http://aktin.org/ns/aggregate/r";
	@XmlElement
	Source source;
	@XmlElement
	List<Resource> resource;
	/**
	 * List of result file entries which will be generated by the r-script execution.
	 * For dynamically generated entries, see {@link #resultList}
	 */
	@XmlElement
	List<Result> result;

	/**
	 * Dynamically generated file names are written to the {@code <result-list file="listing.txt"/>}
	 * This file contains lines of the form {@code filename=mime/subtype} e.g. {@code file.txt=text/plain}.
	 */
	@XmlElement(name="result-list")
	ResultList resultList;
}
