version: '3.7'
services:
  aktin-client:
    container_name: aktin-client
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    volumes:
      - ./client-exec-scripts/echo.sh:/opt/codex-aktin/echo.sh
      - ./client-exec-scripts/call-cql.sh:/opt/codex-aktin/call-cql.sh
      - ./client-exec-scripts/execute-cql.sh:/opt/codex-aktin/execute-cql.sh
      - ./client-exec-scripts/call-flare.sh:/opt/codex-aktin/call-flare.sh
      - ./sysproc.properties:/opt/codex-aktin/sysproc.properties
