version: '3.7'
services:
  aktin-broker:
    #entrypoint: sh -c "tail -f /dev/null"
    build:
      context: ../..
      dockerfile: docker/aktin-broker/Dockerfile
    ports:
      - ${AKTIN_BROKER_PORT:-127.0.0.1:8080}:8080
    environment:
      LOG_LEVEL: ${AKTIN_BROKER_LOG_LEVEL:-INFO}
      PASSWORD: ${AKTIN_ADMIN_PW:-changeme}
    volumes:
    - ./api-keys.properties:/opt/codex-aktin/api-keys.properties
