version: '3.7'
services:
  aktin-client:
    container_name: aktin-client
    environment: 
      BROKER_REQUEST_MEDIATYPE: ${BROKER_REQUEST_MEDIATYPE:-text}
      BROKER_RESULT_MEDIATYPE: ${BROKER_RESULT_MEDIATYPE:-application/json}
      BROKER_ENDPOINT_URI: ${BROKER_ENDPOINT_URI:-http://aktin-broker:8080/broker/}
      CLIENT_AUTH_CLASS: ${CLIENT_AUTH_CLASS:-org.aktin.broker.client2.auth.ApiKeyAuthentication}
      CLIENT_AUTH_PARAM: ${CLIENT_AUTH_PARAM:-xxxApiKey123}
      CLIENT_WEBSOCKET_RECONNECT_SECONDS: ${CLIENT_WEBSOCKET_RECONNECT_SECONDS:-10}
      CLIENT_WEBSOCKET_RECONNECT_POLLING: ${CLIENT_WEBSOCKET_RECONNECT_POLLING:-true}
      PROCESS_TIMEOUT_SECONDS: ${PROCESS_TIMEOUT_SECONDS:-60}
      PROCESS_COMMAND: ${PROCESS_COMMAND:-/opt/codex-aktin/echo.sh}
      PROCESS_ARGS: ${PROCESS_ARGS:-10}
      JAVA_OPTS: $JAVA_OPTS
    build:
      context: ../..
      dockerfile: docker/aktin-client/Dockerfile
    volumes:
      - ./client-exec-scripts/echo.sh:/opt/codex-aktin/echo.sh
      - ./client-exec-scripts/return-request.sh:/opt/codex-aktin/return-request.sh
