version: '3.7'
services:
  aktin-client:
    environment: 
      BROKER_REQUEST_MEDIATYPE: ${BROKER_REQUEST_MEDIATYPE:-application/xml}
      BROKER_RESULT_MEDIATYPE: ${BROKER_RESULT_MEDIATYPE:-text/plain}
      BROKER_ENDPOINT_URI: ${BROKER_ENDPOINT_URI:-http://aktin-broker:8080/broker/}
      CLIENT_AUTH_CLASS: ${CLIENT_AUTH_CLASS:-org.aktin.broker.client2.auth.ApiKeyAuthentication}
      CLIENT_AUTH_PARAM: ${CLIENT_AUTH_PARAM:-xxxApiKey123}
      CLIENT_WEBSOCKET_PING_SECONDS: ${CLIENT_WEBSOCKET_PING_SECONDS:-600}
      CLIENT_WEBSOCKET_RECONNECT_SECONDS: ${CLIENT_WEBSOCKET_RECONNECT_SECONDS:-10}
      CLIENT_WEBSOCKET_RECONNECT_POLLING: ${CLIENT_WEBSOCKET_RECONNECT_POLLING:-true}
      PROCESS_TIMEOUT_SECONDS: ${PROCESS_TIMEOUT_SECONDS:-60}
      PROCESS_EXECUTOR_THREADS: ${PROCESS_EXECUTOR_THREADS:-1}
      PROCESS_COMMAND: ${PROCESS_COMMAND:-/opt/codex-aktin/echo.sh}
      PROCESS_ARGS: ${PROCESS_ARGS:-10}
      JAVA_OPTS: $JAVA_OPTS
      LOG_LEVEL: ${AKTIN_CLIENT_LOG_LEVEL:-INFO}
    build:
      context: ../..
      dockerfile: docker/aktin-client/Dockerfile
